### ISSUE TITLE
Version 5.0.0

### ISSUE THREAD

**Issue by maxrimue** [yargs/yargs#519]
It might still take some time until we will get v5.0.0 out, but I thought I would create an issue now already since we already have two things to do in the next major release, and this issue + the label is thought to help organising work on it.

Currently proposed:
- [x] recommend similar commands when no match is found (PR #580).
- [x] Replace `zh.json` with new, identical `zh_CN.json` locale file (PRs #511, #578)
- [x] Remove undocumented alias for `default()` (PR #469, deprecated in #481)
- [x] Make `.demand()` depend on context (Issue #451, PR #582)
- [x] Don't require the command builder to return (Issue #522, PR #549)
- [x] default to `noop` command builder (PR #583)
- [x] default to `fail()` being a global configuration setting (Issue #539, PR #583) we should synchronize with https://github.com/yargs/yargs/issues/455
- [x] Require command directory should work regardless of where invoked (Issue #529, PR #548)
- [x] land @elas7's work on yargs-parser (PRs yargs/yargs-parser#19, #581)
- [x] implement coercion feature, which can be used to address various advanced command parsing asks (Issue #535, PRs yargs/yargs-parser#42, yargs/yargs-parser#47, #581, and #586)

**Comment by ljharb** [comment]
- [ ] Add `.conflicting()` to compliment `.implies()` (#534)

**Comment by bcoe** [comment]
@ljharb in top-level issue now 👍

**Comment by bcoe** [comment]
@ljharb haven't forgotten about `conflicting`, but doesn't look like it's going to make it into the first release of `5.x` :)

**Comment by ljharb** [comment]
That's ok, it'll be semver-minor :-)
