### ISSUE TITLE
Version 7.0.0

### ISSUE THREAD

**Issue by maxrimue** [yargs/yargs#742]
Again, another ticket to have all discussions and info on the next major in one thread. Feel free to propose (or make) changes. Everyone is invited to discuss here!

## Breaking

- [x] ~Remove deprecated `.demand()` in favour of `.demandCommand()` and `.demandOption()` as introduced in v6.6.0 (#740)~ _since we're breaking a ton of stuff in this release, I'm tempted to leave `.demand()` for now (I don't see a reason to add an extra annoyance for folks upgrading)`.
- [x] Alert misuse of yargs API (#739)
- [x] Don't handle program errors within yargs (#455)
- [x] Apply options defined in global scope globally by default
- [x] Rearranged order of precedence for args (#627)
- [x] Rearranged order of precedence for context/default values (#724)
- [x] default commands, finally!

Additionally, we wanted to pull of a readme overhaul. Perhaps a major would be a great time to do this, or we postpone this. Also, we discussed adding certain tutorials to the yargs website ([yargs.github.io/#26](https://github.com/yargs/yargs.github.io/issues/26)), what's the status on that?

cc: @bcoe @nexdrew @lrlna @jameswomack @elas7

**Comment by xstable** [comment]
You also need to remove it from documentation. 
Today I run into the demandCommand()-Error because I give it a try like descriped in the docu.

Can you explain what to use now instead of demandCommand?

**Comment by lrlna** [comment]
nice one @maxrimue ! ✨ 

errrr about tutorials -- i tried and horribly failed; i can't write cohesively thought out things for the life of me :(

**Comment by maxrimue** [comment]
Thanks @lrlna! ✨ 

How about we simply work on this together in the dedicated issue? We could collect ideas first on how to position the tutorials, what they should be about etc., and then eventually write them together in a wip pull request, what do you think? I'm not experienced in this either but I'm sure together we can do diss 😁

**Comment by wtgtybhertgeghgtwtg** [comment]
Will `yargs@7.0.0` keep support for `node@0.12.0` or require `node@4.0.0`?

**Comment by maxrimue** [comment]
@wtgtybhertgeghgtwtg Our plan originally was to drop support for older Node.js versions early this year. Perhaps this next major would be a good time to do that, as both v0.10 and v0.12 are not maintained anymore and insecure to use. What does everyone think about this?

**Comment by bcoe** [comment]
@maxrimue @wtgtybhertgeghgtwtg I was thinking that we remove `0.12` and `0.10` from the testing matrix for TravisCI; not actively start rewriting code to use new language features just yet, but allow yargs' dependencies to gradually drift onto versions that require newer nodes.

**Comment by wtgtybhertgeghgtwtg** [comment]
I think sooner would be better than gradual, if for no other reason than to reduce [the size of the dependency tree](https://github.com/mishoo/UglifyJS2/pull/1302#issuecomment-248611354).

**Comment by bcoe** [comment]
https://github.com/yargs/yargs/issues/659#issuecomment-274211240 another vote for applying options globally by default.

**Comment by bcoe** [comment]
@maxrimue @wtgtybhertgeghgtwtg I've been having a few chats with other folks in the community and at work; given yargs is depended on by such a huge # of libraries, and given that it's used for a lot of [system-level linux-stuff](https://twitter.com/guillaumeQD/status/807917750425440256) (which tends to upgrade slowly) I'm tempted to keep `0.10` and `0.12` support a little bit longer.

For starters, I'd like to reach out to some of our more popular dependents, e.g., [jest](https://github.com/facebook/jest), [atom](https://github.com/atom/atom), etc., and see what there plans are for dropping `0.10`/`0.12`.

One thought I had, was that we could gradually start dropping `0.10` and `0.12` support on some of the _somewhat_ popular libraries in the `yargs` ecosystem to start, and see what the reaction is -- this can act as a canary in the coal mine.

The first library I was thinking of experimenting with is [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul); It's quite popular, has a lot of downloads, but doesn't touch any of the core `nyc` or `yargs` code.

**Comment by wtgtybhertgeghgtwtg** [comment]
`jest` dropped `0.12` some time ago.

**Comment by bcoe** [comment]
@wtgtybhertgeghgtwtg 👍 that's good to know. But I still think I'd like to stay on the side of caution for the `7.x` release; I'm about to remove `0.10`/`0.12` support from my first popular library this afternoon, we'll see if many issues come in as a result.

It's worth noting that dropping `0.10`/`0.12` support will not result in a smaller # of dependencies being used by yargs:

* we're not using any transpilation libraries in yargs, so mainly the net-effect of dropping `0.10`/`0.12` support will be that we can gradually use some lovely language features like `Object.assign`.
* we've already been dropping dependencies from yargs when possible, trying to keep the library size to a minimum -- most recently @maxrimue has been working on removing the `window-size` dependency I believe.

**Comment by wtgtybhertgeghgtwtg** [comment]
Several of the dependencies of `yargs` depend on ponyfills (`number-is-nan`, `code-point-at`, `pinkie-promise`, `is-utf8`).  Bumping the dependencies would remove those ponyfills, but they require `node>=4`.

**Comment by bcoe** [comment]
@wtgtybhertgeghgtwtg I figured this was part of the motivation, and I would like to drop `0.12`/`0.10` soon; I just want to give the community a bit more time potentially -- I'll check with npm's stats next week, and get some #s on total `0.10`/`0.12` downloads -- I actually have enough logs at work that I could even see how many yargs `0.10/0.12` downloads there are specifically.

We have `750,000` downloads a day at this point, and I'd like to make sure a very small percentage are `0.10` before we throw it out.

**Comment by wtgtybhertgeghgtwtg** [comment]
Releasing a `7.0.0` does not mean that `6.0.0` is no longer usable.  People who have to support unsupported versions of `node` will still be able to use older versions of `yargs`.  In fact, the three most popular dependants of `yargs` (`uglify-js`, `sass-graph`, and `defs`) pin to older major releases (`3` or `4`).

**Comment by JaKXz** [comment]
@wtgtybhertgeghgtwtg `yargs` has been around quite a bit longer than the newer projects that have dropped support for non-LTS versions - since v0.10 support has been around for a long time (https://github.com/yargs/yargs/commit/372ffadf486c3cc943d5dba91877b5d412195f50) I understand @bcoe's hesitation... 

That being said, I also think [if the data is not _substantially_ in support of keeping that version, it's definitely] time to move on.

**Comment by bcoe** [comment]
@maxrimue, @JaKXz, @nexdrew, I think we have pulls open for most of the breaking changers that are slated for `yargs@7` -- would love help hammering on the features, and then we can release a candidate to a `7` tag on npm, and test against our various libraries.

**Comment by bcoe** [comment]
I've started a poll on Twitter, regarding whether or not we should retire 0.10/0.12:

https://twitter.com/BenjaminCoe/status/833762452730884099

Would love retweets so that we can get as much feedback as possible.

**Comment by bcoe** [comment]
@maxrimue @nexdrew @JaKXz @lrlna before I promote 7.x.x to `latest`, could folks run against some of their repos? I've upgraded a few of npm's projects.

**Comment by bcoe** [comment]
I should add that we owe a huge thanks to @stevezhu and @pahdo; who helped get 7.x.x over the finish line.

Along with @aashna956, @anshilbhansali who helped test the new functionality with this robot: https://github.com/bcoe/hackillinois-bot
